# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Set up govulncheck tool
description: A simple action for setting up the govulncheck tool in a runner

inputs:
  version:
    description: |
      The version to use for the govulncheck tool.
      Default: latest
    default: latest
    required: false

runs:
  using: composite
  steps:
    - name: Install govulncheck
      shell: bash
      run: go install golang.org/x/vuln/cmd/govulncheck@${{inputs.version}}

    - name: Version Information
      shell: bash
      run: govulncheck -version
