# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Set up the cyclonedx-gomod tool
description: A simple action for setting up the go-licenses tool in a runner

inputs:
  version:
    description: |
      The version to use for the go-licenss tool.
      Default: latest
    default: latest
    required: false

runs:
  using: composite
  steps:
    - name: Install cyclonedx-gomod
      shell: bash
      run: go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@${{inputs.version}}
