name: Generate Vulnerability Report
description: Generates a vulnerability report for Go

inputs:
  packages:
    description: |
      The go package-path to use for the go-licenses tool.
      Default: "./..."
    default: ./...
    required: false
  report-file-name:
    description: The name of the report file
    default: vulnerabilities.sarif
    required: false
  format:
    description: |
      The format to use for the output.
      Default: sarif
    default: sarif
    required: false

outputs:
  output-file:
    description: The path to the generated vulnerability report
    value: ${{steps.report.outputs.output-file}}

runs:
  using: composite
  steps:
    - name: Generate Vulnerability Report
      shell: bash
      id: report
      run: |
        file="${{runner.temp}}}/${{inputs.report-file-name}}"
        govulncheck -format ${{inputs.sarif}} ${{inputs.packages}} > "${file}"
        echo "output-file=${file}" >> "${GITHUB_OUTPUT}"
