# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Vulnerability Scanning

on:
  workflow_call:
    inputs:
      packages:
        type: string
        description: |
          The go package-path to use for the govulncheck tool.
          Default: ./...
        default: ./...
        required: false
      govulncheck-version:
        type: string
        description: |
          The version to use for the govulncheck tool.
          Default: latest.
        default: latest
        required: false

permissions:
  security-events: write

jobs:
  docs:
    name: Vulnerability Scanning
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up govulncheck
      uses: ./actions/golang/setup-govulncheck
      with:
        version: "${{inputs.govulncheck-version}}"

    - name: Check for vulnerabilities
      uses: ./actions/golang/generate-vulnerability-report
      id: report
      with:
        packages: "${{inputs.packages}}"
        format: sarif
        report-file-name: vulnerabilities.sarif

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      if: always()
      with:
        sarif_file: ${{steps.report.outputs.output-file}}
