name: Greet new contributors

on:
  workflow_call:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet new contributors
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.FHIR_BELLOWS_APP_ID }}
          private-key: ${{ secrets.FHIR_BELLOWS_PRIVATE_KEY }}

      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ github.token }}
          issue-message: |
            Hi, @${{ github.actor }}, thank you for opening an issue!

            Since you're a first-time contributor to our organization, please make sure that you
            have reviewed and are familiar with the following contributor documentation:

            * [Contributing Guidelines](https://github.com/friendly-fhir/.github/blob/master/CONTRIBUTING.md)
            * [Code of Conduct](https://github.com/friendly-fhir/.github/blob/master/CODE_OF_CONDUCT.md)
            * [Security Policy](https://github.com/friendly-fhir/.github/blob/master/SECURITY.md)
            * [Governance Model](https://github.com/friendly-fhir/.github/blob/master/GOVERNANCE.md)

            If you have any questions, please feel free to ask, and a human will
            get back to you! 🙂

            Otherwise, we'll prioritize this issue and get back to you when we can.

          pr-message: |
            Hi, @${{ github.actor }}, thank you for contributing! 🚀

            Since you're a first-time contributor to our organization, please make sure that you
            have reviewed and are familiar with the following contributor documentation:

            * [Contributing Guidelines](https://github.com/friendly-fhir/.github/blob/master/CONTRIBUTING.md)
            * [Code of Conduct](https://github.com/friendly-fhir/.github/blob/master/CODE_OF_CONDUCT.md)
            * [Security Policy](https://github.com/friendly-fhir/.github/blob/master/SECURITY.md)
            * [Governance Model](https://github.com/friendly-fhir/.github/blob/master/GOVERNANCE.md)

            If you have any questions, please feel free to ask and a human will
            get back to you! 🙂

            Otherwise, hang-tight for a review from a maintainer.
