# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Docker Container (GHCR)

on:
  workflow_call:
    inputs:
      image-name:
        description: The name of the image.
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      app-id:
        description: |
          The ID of the GitHub App to use for authentication.
          If unspecified, the user will be the actor.
        required: false
        type: string
      app-private-key:
        description: |
          The private key of the GitHub App to use for authentication.
          If unspecified, the password will be the github.token -- and must be
          a token with packages: write permissions.
        required: false
        type: string
      dockerfile:
        description: |
          The path to the Dockerfile to build.
          If unspecified, defaults to 'Dockerfile' in the root of the repository.
        required: false
        default: Dockerfile
        type: string
      dry-run:
        description: |
          If true, the workflow will not push the image to the registry.
        required: false
        default: false
        type: boolean
      path:
        description: |
          The path to build. This corresponds to the <path> argument in 'docker build'.
          If unspecified, defaults to '.'
        required: false
        type: string
        default: '.'
    outputs:
      image-id:
        description: The name of the image that was built.
        value: ${{ jobs.deploy.outputs.image-id }}
      version:
        description: The version of the image that was built.
        value: ${{ jobs.deploy.outputs.version }}
      tagged-image-id:
        description: The fully qualified image id that was built.
        value: ${{ jobs.deploy.outputs.tagged-image-id }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  deploy:
    name: Deploy to Container Registry
    runs-on: ubuntu-latest

    outputs:
      image-id: ${{ steps.image.outputs.id }}
      version: ${{ steps.tag.outputs.version }}
      tagged-image-id: ${{ steps.image.outputs.id }}:${{ steps.tag.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate GitHub App
        id: authenticate
        if: ${{ inputs.app-id && inputs.app-private-key }}
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ inputs.app-private-key }}

      - name: Select Token
        id: select
        run: |
          if [[ -n "${{ inputs.app-id }}" && -n "${{ inputs.app-private-key }}" ]]; then
            echo "token=${{ steps.authenticate.outputs.token }}" >> "${GITHUB_OUTPUT}"
          else
            echo "token=${{ github.token }}" >> "${GITHUB_OUTPUT}"
          fi

      - name: Determine image
        id: image
        run: |
          echo "id=ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}" >> "${GITHUB_OUTPUT}"

      - name: Determine tag
        id: tag
        run: |
          # Extract ref prefix for versions and cut the 'v' prefix
          if [[ "${{ github.ref }}" == "refs/tags/v"* ]]; then
            version=$(echo $version | sed -e 's/^v//')
          elif [[ "${{ github.ref }}" == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            version=latest
          else
            version=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          fi

          echo "version=${version}" >> "${GITHUB_OUTPUT}"

      - name: Login to Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.select.outputs.token }}

      - name: Collect label information
        id: label
        run: |
          echo "url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> "${GITHUB_OUTPUT}"
          echo "repo=${{ github.event.repository.name }}" >> "${GITHUB_OUTPUT}"
          echo "owner=${{ github.repository_owner }}" >> "${GITHUB_OUTPUT}"
          echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "${GITHUB_OUTPUT}"

      - name: Build and push image
        id: push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image.outputs.id }}:${{ steps.tag.outputs.version }}
          labels: |
            org.friendly-fhir.run.number=${{ github.run_number }}"
            org.friendly-fhir.run.attempt=${{ github.run_attempt }}"
            org.friendly-fhir.run.actor=${{ github.actor }}"
            org.friendly-fhir.run.event=${{ github.event_name }}"
            org.friendly-fhir.run=${{ github.run_id }}"
            org.friendly-fhir.source.sha=${{ github.sha }}"
            org.friendly-fhir.source.ref=${{ github.ref }}"
            org.friendly-fhir.source.repo=${{ steps.label.outputs.repo }}"
            org.friendly-fhir.source.owner=${{ steps.label.outputs.owner }}"
            org.friendly-fhir.source=${{ steps.label.outputs.url }}"
            org.friendly-fhir.build-time=${{ steps.label.outputs.timestamp }}"

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ steps.image.outputs.id }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
          github-token: ${{ github.token }}
